# vim: tw=80
baseURL = 'https://blog.juzam.pro/'
languageCode = 'en-us'
title = "The Learning Loop"
theme = ["PaperMod"]
keywords = ["blog", "hardware", "software", "programming languages"]

[params]
author = "Fabio"
ShowShareButtons = true
ShareButtons = ["linkedin", "twitter", "reddit", "bluesky"]
ShowCodeCopyButtons = true

[params.editPost]
url = "https://github.com/fabiojmendes/blog.juzam.pro/blob/master/content"
text = "Suggest Changes"
appendFilePath = true

[params.cover]
responsiveImages = false

[params.homeInfoParams]
title = "Hi there"
content = """
Welcome to my blog.

A space to talk about hardware, software, and techonology in general.
"""

[[params.socialIcons]]
name = "bluesky"
url = "https://bsky.app/profile/fabio.juzam.pro"

[[params.socialIcons]]
name = "github"
url = "https://github.com/fabiojmendes"

[[menus.main]]
name = 'Home'
pageRef = '/'
[[menus.main]]
name = 'Posts'
pageRef = '/posts'
[[menus.main]]
name = 'Search'
pageRef = '/search'
[[menus.main]]
name = 'Tags'
pageRef = '/tags'
[[menus.main]]
name = 'About'
pageRef = '/about'

[outputs]
home = ["HTML", "RSS", "JSON"]
