baseURL = 'https://blog.juzam.pro/'
languageCode = 'en-us'
title = "The Learning Loop"
theme = ["PaperMod"]

[params]
# ShowToc = true
ShowShareButtons = true
ShareButtons = ["linkedin", "twitter", "reddit", "bluesky"]
ShowCodeCopyButtons = true

[params.editPost]
url = "https://github.com/fabiojmendes/blog.juzam.pro/content"
text = "Suggest Changes"
appendFilePath = true

[params.homeInfoParams]
title = "Hi there"
content = """
Welcome to my blog.

Taking a page from swyx's book, I will use this space to
[lean in public](https://www.swyx.io/learn-in-public).
"""

[[params.socialIcons]]
name = "bluesky"
url = "https://bsky.app/profile/fabio.juzam.pro"

[[params.socialIcons]]
name = "github"
url = "https://github.com/fabiojmendes"

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10
[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20
[[menus.main]]
name = 'Search'
pageRef = '/search'
weight = 30
[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 40

[outputs]
home = ["HTML", "RSS", "JSON"]
